### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by arachmani** [oVirt/ovirt-dwh#36]
ovirt-engine-dwh build failed - https://copr.fedorainfracloud.org/coprs/ovirt/ovirt-master-snapshot/build/4388495/
builder-live.log.gz - https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/srpm-builds/04388495/builder-live.log.gz

**Comment by avlitman** [comment]
Build is now successful.
